### PR TITLE
Fixed table width issue in README.MD, renamed license folder, added 843 and 230, updated README.MD

### PR DESCRIPTION
**Pull request by myteron**
README.MD tables where in different width. Using div did not work, adding img to last row allows forcing a width.

LICENSE folder: GitHub expect's a license folder to be named LICENSE not licenses, renamed it.

added code for rule 230, 843 and updated README.

### CODE REVIEW

**Comment by myteron** [comment]
+1

**Comment by davidmather** [comment]
+1

**Comment by BartyBoi1128** [comment]
Test

**Comment by tommcd** [comment]
+1

**Comment by myteron** [comment]
-1 the img is supposed to be in the last row and not in the title. Must check if this pull request is old.

**Pull request closed without merging**
